name-template: 'v$NEXT_PATCH_VERSION'
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
categories:
  - title: '🚀 Features'
    labels: ['feat', 'feature']
  - title: '🐛 Fixes'
    labels: ['fix', 'bug']
  - title: '🧰 Maintenance'
    labels: ['chore', 'refactor', 'docs']
  - title: '🛡️ Security'
    labels: ['security']

exclude-labels:
  - 'skip-changelog'

template: |
  ## Changes
  $CHANGES

tag-template: 'v$NEXT_PATCH_VERSION'
