title = "navaa secret scan"

[allowlist]
description = "allowed patterns and paths (docs, examples, dummy keys)"
# Known false-positive patterns or dummy placeholders
regexes = [
  'dummy_(key|secret)_[a-z0-9]{6,}',
  'example_(token|key)_[A-Za-z0-9]{8,}',
]
# Exclude docs and images from scanning (adjust as needed)
paths = [
  'docs/',
  'README.md',
  'public/',
]

[rule."OpenAI API Key"]
description = "OpenAI API key format"
regex = '''sk-[A-Za-z0-9]{20,}'''
tags = ["key", "openai"]

[rule."Stripe Secret"]
description = "Stripe secret key"
regex = '''sk_(test|live)_[A-Za-z0-9]{16,}'''
tags = ["key", "stripe"]

[rule."Supabase Service Role"]
description = "Supabase service role key"
regex = '''(eyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,})'''
tags = ["key", "jwt", "supabase"]

[rule."Generic High Entropy"]
description = "Generic high-entropy string"
# basic high-entropy candidate; tuned to reduce noise
regex = '''(?i)\b([A-Za-z0-9+/]{32,}=*)\b'''
tag = "entropy"
